name: End to End Tests

on:
  deployment:
    types: [completed]

jobs:
  run-e2es:
    runs-on: ubuntu-latest
    if: github.event.deployment.state == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.deployment.sha }}
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        if: ${{ github.event.deployment.environment_url != '' }}
        run: npx playwright test
        env:
          BASE_URL: ${{ github.event.deployment.environment_url }}